### ISSUE TITLE
Outdated Extension Docs/Pages

### ISSUE THREAD

**Issue by lmangani** [duckdb/community-extensions#188]
I'm not 100% sure if my local caches are playing tricks on me or if this is related to the build pipeline changes for docs but currently the `chsql` and `http_client` extension pages appear to be lagging behind and do not reflect the latest doc changes (or star counters, etc)

I can happily trigger some doc changes for our extensions to confirm and/or test if useful.

**Comment by carlopi** [comment]
thanks, that's on me, I will have a look this afternoon.

**Comment by lmangani** [comment]
Closing on ACK. If you need a guinea pig I'm volounteering 😉
